spring:
  application:
    name: "PROPERTY-MANAGEMENT-PORTAL-BACKEND"
  datasource:
    password: 1
    url: jdbc:postgresql://localhost:5432/waa-final
    username: postgres
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
    defer-datasource-initialization: true
    generate-ddl: true
  sql:
    init:
      mode: always

server:
  port: 8080
sendgrid_key: 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